remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Earthformer: Exploring Space-Time Transformers for Earth System Forecasting"
description: "NeurIPS 2022"
markdown: kramdown
use_math: true